---
- name: Converge
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Apply the motd role
      ansible.builtin.include_role:
        name: example.collection.motd
      vars:
        motd_path: "{{ lookup('env', 'MOLECULE_EPHEMERAL_DIRECTORY') }}/motd"
