---
- name: Verify
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Read the motd file
      ansible.builtin.slurp:
        src: "{{ lookup('env', 'MOLECULE_EPHEMERAL_DIRECTORY') }}/motd"
      register: motd_file

    - name: Check the motd text
      ansible.builtin.assert:
        that:
          - motd_file.content | b64decode == "Authorized use only\n"
