---
- name: Converge
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Apply the issue role
      ansible.builtin.include_role:
        name: example.collection.issue
      vars:
        issue_path: "{{ lookup('env', 'MOLECULE_EPHEMERAL_DIRECTORY') }}/issue"
