---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Read the issue file
      ansible.builtin.slurp:
        src: /etc/issue
      register: issue_file

    - name: Check the banner text
      ansible.builtin.assert:
        that:
          - issue_file.content | b64decode == "Example Linux\n"
