---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Read the users file
      ansible.builtin.slurp:
        src: /opt/app/data/users.txt
      register: users_file

    - name: Check the users
      ansible.builtin.assert:
        that:
          - users_file.content | b64decode == "alice\nbob\n"
