#!/usr/bin/env bash
# Install the local git hooks. Run once per clone.
#
# Installs a pre-push hook that runs tools/check-private-paths.sh, so a push
# fails before it leaves the machine if a protected path is tracked.
set -euo pipefail

repo_root=$(git rev-parse --show-toplevel)
hook="$repo_root/.git/hooks/pre-push"

cat >"$hook" <<'HOOK'
#!/usr/bin/env bash
# Generated by tools/install-hooks.sh. Blocks a push that would publish a
# protected path. Re-run tools/install-hooks.sh to refresh.
set -euo pipefail
repo_root=$(git rev-parse --show-toplevel)
exec "$repo_root/tools/check-private-paths.sh"
HOOK

chmod +x "$hook"
echo "Installed $hook"
